spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow_db
    driver-class-name: org.postgresql.Driver
    username: workflow_user
    password: workflow_pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080